config/routes.rb
R::Application.routes.draw do

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/home', :to => 'pages#home'

  match '/report', :to => 'bookings#report'
  match '/reptest', :to => 'bookings#reptest'
  match '/index2', :to => 'bookings#index2'
  
  get "pages/home"

  get "pages/contact"

  get "pages/about"

  get "pages/help"

  get "home/index"
  
  resources :bookings

   root :to => "pages#home"

end

app/models/booking.rb
class Booking < ActiveRecord::Base
    default_scope :order => 'date'
  
    @@startDate = Date.new(2011, 9, 1)
    @@endDate = Date.new(2012, 7, 31)
 

  def self.startDate
    @@startDate
  end
 
  def self.endDate
    @@endDate
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def authenticate
    authenticate_or_request_with_http_basic do |user_name, password|
      user_name == 'vcbf_editor' && password == 'vcbf_editor'
    end
  end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_filter :authenticate

  # GET /bookings
  # GET /bookings.xml
  def index
    @bookings = Booking.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bookings }
    end
  end

  # GET /bookings/1
  # GET /bookings/1.xml
  def show
    @booking = Booking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @booking }
    end
  end

  # GET /bookings/new
  # GET /bookings/new.xml
  def new
    @booking = Booking.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @booking }
    end
  end

  # GET /bookings/1/edit
  def edit
    @booking = Booking.find(params[:id])
  end

  # POST /bookings
  # POST /bookings.xml
  def create
    @booking = Booking.new(params[:booking])

    respond_to do |format|
      if @booking.save
        format.html { redirect_to(@booking, :notice => 'Booking was successfully created.') }
        format.xml  { render :xml => @booking, :status => :created, :location => @booking }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @booking.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bookings/1
  # PUT /bookings/1.xml
  def update
    @booking = Booking.find(params[:id])

    respond_to do |format|
      if @booking.update_attributes(params[:booking])
        format.html { redirect_to(@booking, :notice => 'Booking was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @booking.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.xml
  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to(bookings_url) }
      format.xml  { head :ok }
    end
  end
  
  def report
    @bookings = Booking.all

    respond_to do |format|
      format.html # report.html.erb
      format.xml  { render :xml => @bookings }
    end
  end

  def reptest
    @bookings = Booking.all

    respond_to do |format|
      format.html # reptest.html.erb
      format.xml  { render :xml => @bookings }
    end
  end

    def index2
    @bookings = Booking.all

    respond_to do |format|
      format.html # index2.html.erb
      format.xml  { render :xml => @bookings }
    end
  end

  
 end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end
  
  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
    base_title = "Video Conference Booking"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end  



end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ref %>: 
    <%= f.text_field :ref %>
  </div>
  <div class="field">
    <%= f.label :fname %>: 
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %>: 
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :dept %>: 
    <%= f.text_field :dept %>
  </div>
  <div class="field">
    <%= f.label :address %>: 
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :email %>: 
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telephone %>: 
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :title %>: 
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %>: 
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :start %>: 
    <%= f.time_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %>: 
    <%= f.time_select :end %>
  </div>
  <div class="field">
    <%= f.label :ppt %>: Yes <%= f.radio_button(:ppt, 'Y') %> No <%= f.radio_button(:ppt, 'N') %> 
  </div> 
  <div class="field">
    <%= f.label :name1 %>: 
    <%= f.text_field :name1 %>
  </div>
  <div class="field">
    <%= f.label :chair1 %>: 
    <%= f.text_field :chair1 %>
  </div>
  <div class="field">
    <%= f.label :part1 %>: 
    <%= f.text_field :part1 %>
  </div>
  <div class="field">
    <%= f.label :room1 %>: 
    <%= f.text_field :room1 %>
  </div>
  <div class="field">
    <%= f.label :tname1 %>: 
    <%= f.text_field :tname1 %>
  </div>
  <div class="field">
    <%= f.label :temail1 %>: 
    <%= f.text_field :temail1 %>
  </div>
  <div class="field">
    <%= f.label :tphone1 %>: 
    <%= f.text_field :tphone1 %>
  </div>
  <div class="field">
    <%= f.label :name2 %>: 
    <%= f.text_field :name2 %>
  </div>
  <div class="field">
    <%= f.label :chair2 %>: 
    <%= f.text_field :chair2 %>
  </div>
  <div class="field">
    <%= f.label :part2 %>: 
    <%= f.text_field :part2 %>
  </div>
  <div class="field">
    <%= f.label :room2 %>: 
    <%= f.text_field :room2 %>
  </div>
  <div class="field">
    <%= f.label :tname2 %>: 
    <%= f.text_field :tname2 %>
  </div>
  <div class="field">
    <%= f.label :temail2 %>: 
    <%= f.text_field :temail2 %>
  </div>
  <div class="field">
    <%= f.label :tphone2 %>: 
    <%= f.text_field :tphone2 %>
  </div>
  <div class="field">
    <%= f.label :name3 %>: 
    <%= f.text_field :name3 %>
  </div>
  <div class="field">
    <%= f.label :chair3 %>: 
    <%= f.text_field :chair3 %>
  </div>
  <div class="field">
    <%= f.label :part3 %>: 
    <%= f.text_field :part3 %>
  </div>
  <div class="field">
    <%= f.label :room3 %>: 
    <%= f.text_field :room3 %>
  </div>
  <div class="field">
    <%= f.label :tname3 %>: 
    <%= f.text_field :tname3 %>
  </div>
  <div class="field">
    <%= f.label :temail3 %>: 
    <%= f.text_field :temail3 %>
  </div>
  <div class="field">
    <%= f.label :tphone3 %>: 
    <%= f.text_field :tphone3 %>
  </div>
  <div class="field">
    <%= f.label :name4 %>: 
    <%= f.text_field :name4 %>
  </div>
  <div class="field">
    <%= f.label :chair4 %>: 
    <%= f.text_field :chair4 %>
  </div>
  <div class="field">
    <%= f.label :part4 %>: 
    <%= f.text_field :part4 %>
  </div>
  <div class="field">
    <%= f.label :room4 %>: 
    <%= f.text_field :room4 %>
  </div>
  <div class="field">
    <%= f.label :tname4 %>: 
    <%= f.text_field :tname4 %>
  </div>
  <div class="field">
    <%= f.label :temail4 %>: 
    <%= f.text_field :temail4 %>
  </div>
  <div class="field">
    <%= f.label :tphone4 %>: 
    <%= f.text_field :tphone4 %>
  </div>
  <div class="field">
    <%= f.label :other %>: 
    <%= f.text_field :other %>
  </div>
  <div class="field">
    <%= f.label :approved %>: Yes <%= f.radio_button(:approved, 'Y') %> No <%= f.radio_button(:approved, 'N') %> 
  </div>  
  <div class="field">
    <%= f.label :notes %>: 
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1>Listing bookings</h1>

<table>
  <tr>
    <th>Ref</th>
    <th>Fname</th>
    <th>Lname</th>
    <th>Dept</th>
    <th>Address</th>
    <th>Email</th>
    <th>Telephone</th>
    <th>Title</th>
    <th>Date</th>
    <th>Start</th>
    <th>End</th>
    <th>Ppt</th>
    <th>Name1</th>
    <th>Chair1</th>
    <th>Part1</th>
    <th>Room1</th>
    <th>Technician</th>
    <th>Name2</th>
    <th>Chair2</th>
    <th>Part2</th>
    <th>Room2</th>
    <th>Technician</th>
    <th>Name3</th>
    <th>Chair3</th>
    <th>Part3</th>
    <th>Room3</th>
    <th>Technician</th>
    <th>Name4</th>
    <th>Chair4</th>
    <th>Part4</th>
    <th>Room4</th>
    <th>Technician</th>
    <th>Other</th>
    <th>Approved</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bookings.each do |booking| %>
  <tr>
    <td><%= booking.ref %></td>
    <td><%= booking.fname %></td>
    <td><%= booking.lname %></td>
    <td><%= booking.dept %></td>
    <td><%= booking.address %></td>
    <td><%= booking.email %></td>
    <td><%= booking.telephone %></td>
    <td><%= booking.title %></td>
    <td><%= booking.date %></td>
    <td><%= booking.start %></td>
    <td><%= booking.end %></td>
    <td><%= booking.ppt %></td>
    <td><%= booking.name1 %></td>
    <td><%= booking.chair1 %></td>
    <td><%= booking.part1 %></td>
    <td><%= booking.room1 %></td>
    <td><%= booking.tname1 %>, <%= booking.temail1 %>, <%= booking.tphone1 %></td>
    <td><%= booking.name2 %></td>
    <td><%= booking.chair2 %></td>
    <td><%= booking.part2 %></td>
    <td><%= booking.room2 %></td>
    <td><%= booking.tname2 %>, <%= booking.temail2 %>, <%= booking.tphone2 %></td>
    <td><%= booking.name3 %></td>
    <td><%= booking.chair3 %></td>
    <td><%= booking.part3 %></td>
    <td><%= booking.room3 %></td>
    <td><%= booking.tname3 %>, <%= booking.temail3 %>, <%= booking.tphone3 %></td>
    <td><%= booking.name4 %></td>
    <td><%= booking.chair4 %></td>
    <td><%= booking.part4 %></td>
    <td><%= booking.room4 %></td>
    <td><%= booking.tname4 %>, <%= booking.temail4 %>, <%= booking.tphone4 %></td>
    <td><%= booking.other %></td>
    <td><%= booking.approved %></td>
    <td><%= booking.notes %></td>
    <td><%= link_to 'Show', booking %></td>
    <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
    <td><%= link_to 'Destroy', booking, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/index2.html.erb
<div id="booking_list">
<h1>Listing bookings</h1>

<table>
<% @bookings.each do |booking| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>" >
    <td><%= booking.date %></td>
    <td><%= booking.fname %> <%= booking.lname %></td>
    <td><%= booking.start.strftime("%H:%M") %>-<%= booking.end.strftime("%H:%M") %></td>
    <td><%= booking.title %></td>
    <td><%= booking.name1 %><br />
        <%= booking.name2 %><br />
        <%= booking.name3 %><br />
        <%= booking.name4 %></td>
    <td><%= booking.notes %></td>

    <td><%= link_to 'Show', booking %><br />
        <%= link_to 'Edit', edit_booking_path(booking) %><br />
        <%= link_to 'Destroy', booking, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
</div>

<br />

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/report.html.erb
<% dept_sess = { "Information and Learning Services Central (Information and Learning Services)" => 0 } %>
<% dept_hours = { "Information and Learning Services Central (Information and Learning Services)" => 0 } %>

<%= form_for(:booking) do |f| %>


 <div class="field">
    <%= f.label "Report from" %>: <%= f.date_select :startDate, {:default => { :year => 2010, :month => 8, :day => 1 }}, :onchange => "this.form.submit();"  %>
    <%= f.label "Until" %>: <%= f.date_select :endDate, {:default => { :year => 2012, :month => 7, :day => 31 }}, :onchange => "this.form.submit();"   %>
  </div>

<% end %>



<% @bookings.each do |booking| %>
  <%  duration = (booking.end - booking.start) / 3600 %>
  <%  if dept_sess[booking.dept] != nil %>
  <%     dept_sess[booking.dept] = dept_sess[booking.dept] + 1 %>
  <%     dept_hours[booking.dept] = dept_hours[booking.dept] + duration %>
  <%  else %>
  <%    dept_sess[booking.dept] = 1 %>
  <%    dept_hours[booking.dept] = duration %>
  <%  end %>
<% end %>
  
<br />  
<table>
  <tr><th>Department</th><th>Bookings</th><th>Total Hours</th><tr>
  <% dept_sess.each do |name,count| %>
  <tr>
    <td><%= name %></td>
    <td><%= count %></td>
    <td><%= dept_hours[name] %></td>
  </tr>
  <% end %>

</table>

app/views/bookings/reptest.html.erb
<% dept_sess = { "Information and Learning Services Central (Information and Learning Services)" => 0 } %>
<% dept_hours = { "Information and Learning Services Central (Information and Learning Services)" => 0 } %>

<%= form_for(:booking) do |f| %>


 <div class="field">
    <%= f.label "Report from" %>: <%= f.date_select Booking.startDate %>
    <%= f.label "Until" %>: <%= f.date_select :endDate, :default => { :year => 2012, :month => 7, :day => 31 } %>
  </div>

<% end %>


<% results = Array.new %>
<% @bookings.each do |booking| %> 
<%   if  booking.date > booking.startDate %>
<%      if booking.date < booking.endDate %>
<%        results.push booking            %>
<%      end   %>
<%   end  %>                
<% end %>


<% results.each do |booking| %>
  <%  duration = (booking.end - booking.start) / 3600 %>
  <%  if dept_sess[booking.dept] != nil %>
  <%     dept_sess[booking.dept] = dept_sess[booking.dept] + 1 %>
  <%     dept_hours[booking.dept] = dept_hours[booking.dept] + duration %>
  <%  else %>
  <%    dept_sess[booking.dept] = 1 %>
  <%    dept_hours[booking.dept] = duration %>
  <%  end %>
<% end %>
  
<br />  
<table>
  <tr><th>Department</th><th>Bookings</th><th>Total Hours</th><tr>
  <% dept_sess.each do |name,count| %>
  <tr>
    <td><%= name %></td>
    <td><%= count %></td>
    <td><%= dept_hours[name] %></td>
  </tr>
  <% end %>

</table>

app/views/bookings/show.html.erb
<h2>Show Booking: <%= @booking.id %></h2>

<table>
<tr>
  <td><b>Ref:</b></td>
  <td><%= @booking.ref %></td>
</tr>

<tr>
  <td><b>Name:</b></td>
  <td><%= @booking.fname %> <%= @booking.lname %></td>
</tr>

<tr>
  <td><b>Dept:</b></td>
  <td><%= @booking.dept %></td>
</tr>

<tr>
  <td><b>Address:</b></td>
  <td><%= @booking.address %></td>
</tr>

<tr>
  <td><b>Email:</b></td>
  <td><%= @booking.email %></td>
</tr>

<tr>
  <td><b>Telephone:</b></td>
  <td><%= @booking.telephone %></td>
</tr>

<tr>
  <td><b>Title:</b></td>
  <td><%= @booking.title %></td>
</tr>

<tr>
  <td><b>Date:</b></td>
  <td><%= @booking.date %></td>
</tr>

<tr>
  <td><b>Time:</b></td>
  <td><%= @booking.start.strftime("%H:%M") %> - <%=@booking.end.strftime("%H:%M") %></td>
</tr>

<tr>
  <td><b>Ppt:</b></td>
  <td><%= @booking.ppt %></td>
</tr>

<tr>
  <td><b>Name1:</b></td>
  <td><%= @booking.name1 %></td>
</tr>

<tr>
  <td><b>Chair1:</b></td>
  <td><%= @booking.chair1 %></td>
</tr>

<tr>
  <td><b>Part1:</b></td>
  <td><%= @booking.part1 %></td>
</tr>

<tr>
  <td><b>Room1:</b></td>
  <td><%= @booking.room1 %></td>
</tr>

<tr>
  <td><b>Technician (external): </b></td>
  <td><%= @booking.tname1 %> : <%= @booking.temail1 %> : <%= @booking.tphone1 %></td>
</tr>

<tr>
  <td><b>Name2:</b></td>
  <td><%= @booking.name2 %></td>
</tr>

<tr>
  <td><b>Chair2:</b></td>
  <td><%= @booking.chair2 %></td>
</tr>

<tr>
  <td><b>Part2:</b></td>
  <td><%= @booking.part2 %></td>
</tr>

<tr>
  <td><b>Room2:</b></td>
  <td><%= @booking.room2 %></td>
</tr>

<tr>
  <td><b>Technician (external): </b></td>
  <td><%= @booking.tname2 %> : <%= @booking.temail2 %> : <%= @booking.tphone2 %></td>
</tr>

<tr>
  <td><b>Name3:</b></td>
  <td><%= @booking.name3 %></td>
</tr>

<tr>
  <td><b>Chair3:</b></td>
  <td><%= @booking.chair3 %></td>
</tr>

<tr>
  <td><b>Part3:</b></td>
  <td><%= @booking.part3 %></td>
</tr>

<tr>
  <td><b>Room3:</b></td>
  <td><%= @booking.room3 %></td>
</tr>

<tr>
  <td><b>Technician (external): </b></td>
  <td><%= @booking.tname3 %> : <%= @booking.temail3 %> : <%= @booking.tphone3 %></td>
</tr>

<tr>
  <td><b>Name4:</b></td>
  <td><%= @booking.name4 %></td>
</tr>

<tr>
  <td><b>Chair4:</b></td>
  <td><%= @booking.chair4 %></td>
</tr>

<tr>
  <td><b>Part4:</b></td>
  <td><%= @booking.part4 %></td>
</tr>

<tr>
  <td><b>Room4:</b></td>
  <td><%= @booking.room4 %></td>
</tr>

<tr>
  <td><b>Technician (external): </b></td>
  <td><%= @booking.tname4 %> : <%= @booking.temail4 %> : <%= @booking.tphone4 %></td>
</tr>

<tr>
  <td><b>Other:</b></td>
  <td><%= @booking.other %></td>
</tr>

<tr>
  <td><b>Approved:</b></td>
  <td><%= @booking.approved %></td>
</tr>

<tr>
  <td><b>Notes:</b></td>
  <td><%= @booking.notes %></td>
</tr>

</table>


<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/home/index.html.erb
<h1>Video conference - Bookings</h1>
<p>
<br />
<%= link_to "Bookings", bookings_path %> <br />

</p>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Report", report_path %></li>    
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://erdt.plymouth.ac.uk/vcbf">Booking Form</a></li>
    </ul>
  <nav>
</footer>

app/views/layouts/_header.html.erb
    <header>
      <%= image_tag("rails.png", :alt => "Insert logo here", :class => "round") %>
      <nav class="round">
       <ul>
         <li><%= link_to "Home", home_path %></li>
         <li><a href="https://staff.plymouth.ac.uk/vidlink/">Help</a></li>
       </ul>
      </nav>
    </header>

app/views/layouts/_stylesheets.html.erb
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>
</head>
<body>
<div class="container">
  <%= render 'layouts/header' %>  

  <section class="round">
    <%= yield %>
  </section>


  <%= render 'layouts/footer' %>  
</div>
</body>
</html>

app/views/pages/about.html.erb
<h2>Video Conferencing (VidLink)</h2>
<p>Management of of bookings information</p>

app/views/pages/contact.html.erb
<h2>Contact</h2>
<section>
     <ul>
       <li>Steve Roberts, <a href="mailto:s3roberts@plymouth.ac.uk">s3roberts@plymouth.ac.uk</a>, Tel: 87293 or </li>
       <li>Deni Baldwin, <a href="mailto:deni.baldwin@plymouth.ac.uk">deni.baldwin@plymouth.ac.uk</a>, Tel: 88722</li>
</ul>


</section>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Video Conference Booking Management</h1>
<p>
<%= link_to "Bookings", bookings_path %> <br />
<%= link_to "- tidier", index2_path %> <br />
</p>